namespace Scape05.Misc;

/// <summary>
/// Server to client opcodes
/// </summary>
public enum ServerOpCodes : byte
{
    CONFIG_SET = 36,
    MSG_SEND = 253,
    SYSTEM_UPDATE_SECS = 114,
    DISCONNECT = 109,

    PLAYER_UPDATE = 81,
    PLAYER_STATUS = 249,
    PLAYER_SKILL = 134,
    PLAYER_LOCATION = 85,
    PLAYER_RUN_ENERGY = 110,
    PLAYER_WEIGHT = 240,
    PLAYER_RIGHTCLICK = 104,
    PLAYER_INTO_OBJ = 147,

    CHAT_SETTINGS = 206,
    CHAT_PRIVATE = 196,

    ITEM_ALL_CLEAR = 72,
    ITEM_SET = 53,
    ITEM_SLOT_SET = 34,

    ANIM_ALL_RESET = 1,
    ANIM_SET = 4,
    MULTICOMBAT = 61,

    NPC_UPDATE = 65,
    NPC_ICON = 254,

    OBJ_ADD = 151,
    OBJ_REMOVE = 101,
    OBJ_ANIMATE = 160,

    PROJECTILE = 117,

    FLOORITEM_ADD = 44,
    FLOORITEM_REMOVE = 156,
    FLOORITEM_REMOVE_SPAWNED = 64,
    FLOORITEM_UNKNOWN = 84,
    FLOORITEM_UNKNOWN2 = 215,

    REGION_UPDATE = 60,
    REGION_LOAD = 73,
    REGION_CONSTRUCT = 241,

    SONG_PLAY = 74,
    SONG_QUEUE = 121,
    SOUND_PLAY = 174,
    SOUND_PLAYAT = 105,

    CAMERA_SHAKE = 35,
    CAMERA_SPIN = 166,
    CAMERA_RESET = 107,
    CAMERA_TURN = 177,

    SIDEBAR_FLASH = 24,
    SIDEBAR_SET = 106,
    SIDEBAR_INTF_ASSIGN = 71,

    INTF_WELCOME = 176,
    INTF_SHOW = 97,
    INTF_CLEAR = 219,
    INTF_TEXT_ADD = 126,
    INTF_COLOR_SET = 122,
    INTF_MODEL_SET = 254,
    INTF_MODEL_ANIM = 200,
    INTF_MODEL_ROTATE = 230,
    INTF_MODEL_ZOOM = 246,
    INTF_CHAT_ADD = 164,
    INTF_HIDDEN = 171,
    INTF_WALKABLE = 208,
    INTF_INV_HUD = 248,
    INTF_INV_REPLACE = 142,
    INTF_OFFSET = 70,
    INTF_SCROLL_SET = 79,
    INTF_ENTER_NAME = 187,
    INTF_ENTER_AMT = 27,

    BTN_ALL_RESET = 68,
    BTN_SET = 87,

    FRIENDLIST_STATUS = 221,
    FRIEND_ADD = 50,
    IGNORE_ADD = 214,

    MINIMAP_CLR_FLAG = 78,
    MINIMAP_STATE = 99
}